apiVersion: v1
kind: Secret
metadata:  
  name: db-credentials
type: Opaque
data:
  SQL_USER: c3FsYWRtaW5sTWY2ODM3
  SQL_PASSWORD: ZGVtbyFwYXNzMTIz
  SQL_SERVER: c3Fsc2VydmVybG1mNjgzNy5kYXRhYmFzZS53aW5kb3dzLm5ldA==
  SQL_DBNAME: bXlkcml2aW5nREI=
